"""
The GGNN cover algebra, made explicit.

A *cover* is built from directed subgraphs; the monoidal homomorphism Tr sends a
directed subgraph to its matrix form, and -- crucially -- sends subgraph
composition to matrix multiplication (path concatenation). This module makes that
machinery first-class instead of implicit, and defines three cover families whose
matrix forms feed the models:

  * walk cover        : the monoid generated by the edge cover, Tr(D^t) = A^t.
  * reachability cover: the union cover, sign(sum_t A^t).
  * sieve cover       : a precomposition-refined cover that inspects the structure
                        *among* the elements covering each node (its neighbourhood
                        subgraph). This is the piece that distinguishes graphs the
                        walk/reachability covers cannot (e.g. cospectral SRGs).

`check_homomorphism` verifies Tr(D1 . D2) == Tr(D1) . Tr(D2) on a random example.
"""
from __future__ import annotations
import numpy as np
from .operators import n_components


def Tr(D):
    """Matrix form of a directed subgraph (here D is already its 0/1 matrix)."""
    return (np.asarray(D) > 0).astype(np.float32)


def compose(D1, D2):
    """Subgraph composition -> boolean matrix product (one step of concatenation)."""
    return ((Tr(D1) @ Tr(D2)) > 0).astype(np.float32)


def check_homomorphism(seed=0, n=8):
    """Demonstrate Tr is a monoid homomorphism: Tr(D1 o D2) = Tr(D1) Tr(D2)."""
    rng = np.random.default_rng(seed)
    D1 = (rng.random((n, n)) < 0.3).astype(np.float32)
    D2 = (rng.random((n, n)) < 0.3).astype(np.float32)
    return np.array_equal(compose(D1, D2), ((Tr(D1) @ Tr(D2)) > 0))


# ---- cover families -> per-node feature blocks --------------------------------

def walk_cover(A, K):
    """Per-node features from the walk cover: walks arriving and closed walks.
    For a regular graph these are constant across nodes, which is exactly why the
    walk cover alone cannot separate cospectral regular graphs."""
    n = A.shape[0]; ones = np.ones((n, 1), np.float32)
    feats, P = [], np.eye(n, dtype=np.float32)
    for _ in range(K):
        P = P @ A
        feats.append((P @ ones).reshape(n))
        feats.append(np.diag(P).copy())
    return np.stack(feats, 1).astype(np.float32)


def reachability_cover(A, K):
    n = A.shape[0]; R = np.eye(n, dtype=np.float32); P = np.eye(n, dtype=np.float32)
    for _ in range(K):
        P = P @ A; R = ((R + P) > 0).astype(np.float32)
    np.fill_diagonal(R, 0.0)
    return (R.sum(1) / max(n - 1, 1)).reshape(n, 1).astype(np.float32)


def sieve_cover(A, L=6):
    """Per-node sieve-cover features: the structure of the subgraph induced on a
    node's neighbours (the elements covering it). Captures arrangement, not just
    counts -- the refinement that separates cospectral SRGs.

    Per node: [#triangles in N(v), #components of N(v), closed walks of length
    3..L within N(v)].
    """
    n = A.shape[0]
    rows = []
    for v in range(n):
        nb = np.nonzero(A[v])[0]
        if len(nb) == 0:
            rows.append([0.0, 0.0] + [0.0] * (L - 2)); continue
        B = A[np.ix_(nb, nb)]
        tri = np.trace(B @ B @ B) / 6.0
        comps = float(n_components(B))
        cw, P = [], B.copy()
        P = B @ B                                   # start at length 2
        for _ in range(3, L + 1):
            P = P @ B
            cw.append(float(np.trace(P)))
        rows.append([float(tri), comps] + cw)
    return np.asarray(rows, np.float32)
